# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- feature/*

variables:
  dockerRegisteryServiceConnection: 'RegisteryConnection'
  imageRepository: 'weight-tracker-app'
  containerRegistery: ''
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildNumber)'

pool:
  name: MyPool
  demands:
   - agent.name -equals MyAgent


stages:

# Continuous Integration Process
- stage: CI
  jobs:
  - job: BuildAndPushDocker
    workspace: 
      clean: all
    steps:
    - task: DownloadSecureFile@1
      inputs:
        secureFile: '.env'
      
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(System.DefaultWorkingDirectory)'
      inputs:
        SourceFolder: '$(Agent.TempDirectory)'
        Contents: .env
        TargetFolder: '$(System.DefaultWorkingDirectory)'

    - task: Docker@2
      inputs:
        containerRegistry: $(dockerRegisteryServiceConnection)
        repository: $(imageRepository)
        command: 'buildAndPush'
        Dockerfile: $(dockerfilePath)
        tags: |
          $(tag)
    
