# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- feature/*

variables:
  dockerRegisteryServiceConnection: 'privateRegistery'
  imageRepository: 'weight-tracker-app'
  containerRegistery: 'oribootcampacr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildNumber)'

pool: MyPool

stages:

# Continuous Integration Process
- stage: CI
  jobs:
  - job: BuildAndPushDocker
    workspace: 
      clean: all
    steps: 
    - task: Docker@2
      displayName: Build and Push on master branch
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
      inputs:
        containerRegistry: $(dockerRegisteryServiceConnection)
        repository: $(imageRepository)
        command: 'buildAndPush'
        Dockerfile: $(dockerfilePath)
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Build on feature branch
      condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
      inputs:
        command: 'build'
        Dockerfile: '**/Dockerfile'

- stage: Deploy_Staging
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  displayName: Deploy Staging
  jobs:
    - deployment: Deploy_Staging
      variables:
      - group:  StagingVars
      environment: 
        name: StagingEnv
        resourceType: VirtualMachine
      displayName: Deploy
      strategy:
         runOnce:
           deploy:
             steps:
             - template: deploy-template.yml
                  
- stage: Deploy_Production
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  displayName: Deploy Production
  jobs:
    - deployment: Deploy_Production
      variables:
      - group:  ProductionVars
      environment: 
        name: ProductionEnv
        resourceType: VirtualMachine
      displayName: Deploy
      strategy:
         runOnce:
           deploy:
             steps:
             - template: deploy-template.yml
