# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- feature/*

pool:
  name: MyPool
  demands:
   - agent.name -equals MyAgent


stages:

# Continuous Integration Process
- stage: CI
  jobs:
  - job: BuildAndPushDocker
    workspace: 
      clean: all
    steps:
    - task: CmdLine@2
      inputs:
        script: 'sudo apt install docker.io'

    - task: Docker@2
      inputs:
        containerRegistry: 'RegisteryConnection'
        repository: 'MyRepo'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        addPipelineData: false
        addBaseImageData: false
    
