# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- feature/*

variables:
  dockerRegisteryServiceConnection: 'RegisteryConnection'
  imageRepository: 'weight-tracker-app'
  containerRegistery: 'pipelineassignmentregistery.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildNumber)'

pool: MyPool

stages:

# Continuous Integration Process
- stage: CI
  jobs:
  - job: DockerBuild
    workspace: 
      clean: all
    steps: 
    - task: Docker@2
      inputs:
        containerRegistry: $(dockerRegisteryServiceConnection)
        repository: $(imageRepository)
        command: 'build'
        Dockerfile: $(dockerfilePath)
        tags: |
          $(tag)
   