apiVersion : apps/v1
kind: Deployment
metadata:
  name: webapp 
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp 
    spec:
      containers:
        - name: webapp
          image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
          ports:
          - containerPort: 8080
          envFrom:
          - configMapRef:
              name: env-config
