apiVersion : apps/v1
kind: Deployment
metadata:
  name: webapp 
spec:
  replicas: {{.Values.deployment.replicas}}
  selector:
    matchLabels:
      app: webapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: webapp 
    spec:
      containers:
        - name: webapp
          image: {{.Values.deployment.image}}:{{.Values.deployment.tag}}
          ports:
          - containerPort: 80
