apiVersion : apps/v1
kind: Deployment
metadata:
  name: web-app 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app 
    spec:
      containers:
        - name: web-app 
          image: k8sregistery.azurecr.io/weighttracker-img
          ports:
          - containerPort: 80